--- #YAML:1.0
name:               Device-USB-Win32Async
version:            0.31
abstract:           Add async functions to Device::USB
author:
    - Rajstennaj Barrabas <barrabas@barrabas.mv.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Device::USB:  0.3
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
